package com.joetsumap.exception.payload.response;

public enum EExpectedExceptionType {
  VALIDATION_ERROR,
  TARGET_NOT_FOUND,
  ACCESS_DENIED,
  FILE_UPLOAD_ERROR,
  ALREADY_EXISTS,
  UNAUTHORIZED,
  BAD_CREDENTIALS,
  USER_DISABLED,
  USER_LOCKED,
  TRAVELSPOT_IN_MODELCOURSE_NOT_FOUND,
}
